### ISSUE TITLE
配置文件格式兼容问题

### ISSUE THREAD

**Issue by vmlive** [sskaje/ubnt-clash#4]
如果配置文件中proxies节点写成数组的形式如：
{name: 🇭🇰 Hong Kong 06, server: api.1.ss03.net, port: 22356, type: ss, cipher: chacha20-ietf-poly1305, password: 52XXX, udp: true}
似乎程序不能兼容，必须是普通格式才行，如：
    name: 🇭🇰 Hong Kong 09
    type: ss
    server: api.1.ss03.net
    port: 22359
    password: 52XXX
    cipher: chacha20-ietf-poly1305
    udp: true

另外是否计划更新0.4.4版本了？

**Comment by vmlive** [comment]
我的问题，与配置文件格式无关

**Comment by sskaje** [comment]
本来是想攒着 unifi os 的脚本一起发的，但是没空写。

你需要的话，我把现有的版本发出来
