### ISSUE TITLE
订阅地址包含特殊字符，配置订阅 URL时无法输入

### ISSUE THREAD

**Issue by m0nkeyd** [sskaje/ubnt-clash#6]
我服务商给的订阅地址里有个问号，把整个url全转义后Error: Invalid Clash Config应该是不支持转义，请问这个怎么解决呢

**Comment by sskaje** [comment]
@m0nkeyd 方便的话，给我一个 url ？ sskaje [at] gmail

**Comment by m0nkeyd** [comment]
格式大概 https://api.domain.com/client/subscribe?token=xxxxxxxxxxxxxxxxxxx 这样

**Comment by sskaje** [comment]
我用的格式跟你差不多

```
root@ubnt# show interfaces clash 
 clash utun {
     check-interval 30
     config-url https://some.host/subscribe/AZaz09?clash=yyyyyy
     executable clash
     update-interval 14400
 }
[edit]
```

**Comment by m0nkeyd** [comment]
我手敲或者粘贴的时候到问号会出发帮助这样，或许是我putty设置问题？

**Comment by sskaje** [comment]
不可能。
你命令行下 curl 你的地址 试试吧

正常不需要转义，如果真遇到需要转义的，只能给我样例了，测完reset 一下你的token。

再要不然，就死马当活马医，开代理
```
touch /config/clash/USE_PROXY

clashctl.sh start
```

**Comment by m0nkeyd** [comment]
我试了另外一个ssh，在任何状态下输问号都会跳帮助这样，能把这个问号输进去应该就能用了

**Comment by m0nkeyd** [comment]
应该是触发了 https://help.ui.com.cn/articles/900000294526/ 里面提到的 “每种模式都有独立的命令。您可以使用问号 ? 键在两种模式下显示所有可用命令。按 ? 键两次，还可以显示该命令的描述：”这个东西……

**Comment by sskaje** [comment]
@m0nkeyd `sudo su` 切到root再操作

**Comment by m0nkeyd** [comment]
切root就ok了，然后clashctl.sh start还是报Error: Invalid Clash Config，我手动curl了一个clash.config之后报Error: open /config/clash/utun/rulesets/*.yaml: no such file or directory，然后，手动创建目录再去 https://github.com/Loyalsoldier/clash-rules curl了一个yaml之后clash就能跑起来了

**Comment by m0nkeyd** [comment]
还没配PBR路由和DNS，估计配好之后流量就能过去了

**Comment by m0nkeyd** [comment]
搞定了，检查了一下安装的BASH里有复制模板到utun目录下的语句但是没执行成功，也许是因为网络原因跑到哪里中断了。手动照着搞一遍就没问题了

**Comment by fsdrw08** [comment]
另外，在vyos下，要输入问号，则需要在console连接下进行，不能在ssh下输入
