### ISSUE TITLE
启动提示yq Segmentation fault

### ISSUE THREAD

**Issue by Mickyxing** [sskaje/ubnt-clash#7]
root@ubnt:/home/clash# clashctl.sh restart
/usr/bin/clashctl.sh: line 322: 17544 Segmentation fault      yq eval-all --from-file /usr/share/ubnt-clash/one.yq ${config_files[@]} > $CLASH_RUN_ROOT/$DEV/config.yaml

**Comment by sskaje** [comment]
@Mickyxing 你是什么设备？

**Comment by Mickyxing** [comment]
root@ubnt:/var/lib/apt# uname -a
Linux ubnt 3.10.107-UBNT #1 SMP Fri Feb 21 10:42:32 UTC 2020 mips GNU/Linux

**Comment by sskaje** [comment]
有点奇怪，怎么 mips 会下载mipsel的，我看看代码

**Comment by sskaje** [comment]
@Mickyxing 你是什么设备？

**Comment by Mickyxing** [comment]
EdgeRouter X

**Comment by Mickyxing** [comment]
> 

哦哦，太感谢了

**Comment by sskaje** [comment]
@Mickyxing 

更新固件吧，我的是最新的固件，没问题

```
root@ERX:/home/ubnt# yq -V
yq (https://github.com/mikefarah/yq/) version 4.28.2
root@ERX:/home/ubnt# uname -a
Linux ERX 4.14.54-UBNT #1 SMP Tue May 11 13:23:28 UTC 2021 mips GNU/Linux

root@ERX:/home/ubnt# show system image
The system currently has the following image(s) installed:

v2.0.9-hotfix.2.5402463.210511.1317 (running image) (default boot)
```

**Comment by Mickyxing** [comment]
好的好的，那我更新后再试一下，谢谢啦
